import { Inter, Cabin } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const cabin = Cabin({ subsets: ["latin"], weights: ["400", "500", "600", "700"], italic:["normal", "italic"] });

export const metadata = {
  title: "Ali Vayani",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cabin.className}>{children}</body>
    </html>
  );
}
